ignore_Display: false
Sorted_Display: true
special_group:
 - 隆木乡风电场站
 - 连山
 - 旺村电站
 - 滨州临港2GW渔光互补
 - 白音华铝业
 - 南川光伏
 - 构皮滩
 - 青山站
 - 安平光伏电站
 - 乱罗嶂
 - 烟霞升压站
 - 瑞阳光储站
 - 佐龙光储站
 - 鹿江光伏站
 - 阿旗北500千伏
 - 怀南风电厂
 - 永修县光伏场站
 - 都日那风电场
 - 横梁一二期风电厂
 - 坪上风电厂
 - 三坝风电厂
 - 南川天马光伏
 - 沙子一二期风电厂
 - 麒麟一二期风电站
 - 宁夏京能红墩子光伏站
 - 前贡站
 - B1站六合风电场
 - B站祥辉风电场
 - A站瑞和风电场
 - A1站阿荣旗风电场
 - 朝阳一二期风电场
Parallel-display: true 
